version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "python"

    [analyzers.meta]
    runtime_version = "3.x.x"
    max_line_length = 150

[[analyzers]]
name = "docker"

[[transformers]]
name = "black"

[[transformers]]
name = "isort"